apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /{{ .Values.urlAbbrev }}/$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ if .Values.comodoHostPrefix }}{{ .Values.comodoHostPrefix }}-{{ end }}{{ .Values.tenant }}-api.org.com      
      secretName: {{ if .Values.comodoHostPrefix }}{{ .Values.comodoHostPrefix }}-{{ end }}demo-api-ingress-tls
  rules:
    - host: {{ if .Values.comodoHostPrefix }}{{ .Values.comodoHostPrefix }}-{{ end }}demo-api.org.com
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 80
            path: /{{ .Values.urlAbbrev }}(/|$)(.*)
            pathType: ImplementationSpecific
