apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.appName }}-secrets
  name: {{ .Values.appName }}-secrets
  namespace: {{ .Values.namespace }}
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | upper }}: {{ $value }}
  {{- end }}
