apiVersion: v1
kind: Service
metadata:
  annotations:
    template: {{ .Template.Name }}
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.appName }}
